### PR TITLE
fix compile

### PR DESCRIPTION
**Pull request by anzz1**

### CODE REVIEW

**Comment by anzz1** [comment]
It compiles now, but something palette-related is still missing as the icon colors are messed up.
image

**Comment by anzz1** [comment]
Not a super elegant solution but just removing the borders with a image editor fixes it. I didn't touch the palette (in the png) so the unused colors are left behind there.
split_icons_battle

**Comment by anzz1** [comment]
the PIXEL_FILL value was wrong for the palette in question and wrong bg color bled through. 7 -> 9 fixes it.

**Comment by 00mn00** [comment]
Thank you for this, I had a similar issue when I was testing it before uploading and I adjusted the palette file in Photoshop, which fixed it on my end, making me think it was resolved. Clearly not the case!

**Comment by anzz1** [comment]
For future reference, this is how I figured out what was going on:

When you compile, the gbagfx tool converts the png files to the gba graphics format by splitting the data into 4bpp gfx and palette components. This makes it simple to work with a regular image editor as the conversion process is automatic. This 4bpp mode has a maximum of 16 of those 16-color palettes loaded in VRAM at any given time. There is also a 8bpp 1-palette 256-color mode which isn't covered here.

I don't use Photoshop but a free tool called Pixelformer (which while lacking features, has proved to be a great tool for working with sprites) but this is applicable to Photoshop or any other editor for that matter.

So when I opened the "split_icons_battle.png" in PixelFormer, here you can see the palette for it in PixelFormer:
image

Then in VBA there is this great tool in "Tools -> Palette Viewer" where you can view the palette in realtime.

image

The code in FireRed seems to be mostly centered around loading these 16-color palettes to the VRAM one at a time.
Looking more closely, we can figure out what's going on and what went wrong.

image

`LoadPalette(sSplitIcons_Pal, 10 * 0x10, 0x20)` becomes A, marked in red.
`ListMenuLoadStdPalAt(0xD0, 1)` becomes D, marked in maroon.

So for palette A, `FillWindowPixelBuffer(10, PIXEL_FILL(7))` is wrong and fills the background with the scarlet (7) color instead of the off-white (9) we are looking for. For palette D, the same color is index 15.

(To be completely honest, at first I didn't actually figure out what was going on, but just tried random indexes until it worked :smile: . Only afterwards I wanted to know *why* it worked)

**Comment by 00mn00** [comment]
Thank you for the write up, very enlightening! I'll review and merge the pull request(s) on Sunday, as I'm currently away for the next few days. I appreciate your help with the code fixes and tweaking 💪🏻

**Pull request merged**
