### PR TITLE
optimization and cleanup

### PR DESCRIPTION
**Pull request by anzz1**
cont for #2 

* Optimization (CPU):
  - Reduce palette loads from 2 to 1
  - Reduce amount of instructions and function calls

* Optimization (Size/Memory):
  - Category icons share palette with existing types, no extra palette included in compilation

* Code cleanup

### CODE REVIEW

**Comment by 00mn00** [comment]
Thank you for these additions, I'll leave the other branches up in case people prefer text vs image, but in my opinion this is the better alternative.

**Comment by 00mn00** [comment]
Any idea what could be causing this? Happens sometimes and hard to reproduce.
Edit - it seems to be an issue when swapping a move around during battle, then using the move that you swapped.

image

**Comment by anzz1** [comment]
Your icons look wrong, try doing a `make cleanup` before building. I've noticed that with the current toolchain that the compiler doesn't necessarily understand what needs to be rebuilt and so a full cleanup should be always done before the final build.

**Comment by anzz1** [comment]
image
this is how it should look like

from looking at your picture, it seems like your icon is narrower than the original icon is. also the right icon can have problems with the optimization because it uses color not available in the original palette. when rebuilt with `make cleanup`, the icon should not have those orange borders

**Comment by 00mn00** [comment]
I fixed it, for me at least it was changing .width = 5, to .width = 8, for // 8 in battle_bg.c - I like the borders on the icons, for my personal version I have them in, no palette issues either. I redid the png in Aseprite so maybe that fixed whatever the issue was? Either way, if you run into that problem with the black rectangle, you have the potential fix.

**Comment by anzz1** [comment]
Yeah I think too that the borders fit well with the modern icons. I originally removed the borders to fit the restriction of using the original palette but then in my opinion they also fit better along the original type icons.

And yeah if you load a palette with the icons you can use whatever colors you want, it's just that the palette much match the sprite. It's just that the original palette doesn't contain the colors for the borders and wouldn't work but as you're probably already loading a different palette with the modern icons anyway it'll work just fine.

**Comment by 00mn00** [comment]
One finally thing I noticed is that the physical/special icons don't update with the exposed weather ball, I spent the better part of an hour trying to figure it out but no luck.

**Comment by anzz1** [comment]
That is by design, as the three special cases [Weather Ball](https://github.com/00mn00/FRLG-Plus_Custom/blob/57f78c271cfbe931e10ba63501e7f33ca8de0378/src/data/battle_moves.h#L4357) / [Hidden Power](https://github.com/00mn00/FRLG-Plus_Custom/blob/57f78c271cfbe931e10ba63501e7f33ca8de0378/src/data/battle_moves.h#L3321) / [Nature Power](https://github.com/00mn00/FRLG-Plus_Custom/blob/57f78c271cfbe931e10ba63501e7f33ca8de0378/src/data/battle_moves.h#L3741) are `MOVE_CATEGORY_TYPE`  

And as such show the special ?? icon to denote a special (well, not special as category but as being special, you know :)
The type still shows up as normal (well, not normal as category, but youknow :)  

image

If you'd like to have the actual category icons instead of the ??, replace this:
https://github.com/00mn00/FRLG-Plus_Custom/blob/57f78c271cfbe931e10ba63501e7f33ca8de0378/src/battle_util.c#L3202-L3205

with this:
```c
u8 GetBattleMoveCategory(u32 moveId)
{
    return (gBattleMoves[moveId].category == MOVE_CATEGORY_TYPE ? (gBattleMoves[moveId].type < TYPE_MYSTERY ? MOVE_CATEGORY_PHYSICAL : MOVE_CATEGORY_SPECIAL) : gBattleMoves[moveId].category);
}
```

or make it a new function with name GetBattleMoveRealCategory instead of replacing if you still want to be able to get the MOVE_CATEGORY_TYPE somewhere.

**Comment by 00mn00** [comment]
Oh, I wasn't clear, maybe. The only reason MOVE_CATEGORY_TYPE is there is that I couldn't figure out how to have the icon change dynamically if those three moves changed type. Ideally, I'd like it so if MOVE_HIDDEN_POWER is TYPE_GRASS for example, the icon will be special, and if it's TYPE_FIGHTING it'll be physical, essentially.

**Pull request merged**
